"""add on_menu to Category

Revision ID: 887e455a491f
Revises: 
Create Date: 2022-09-27 13:22:52.317256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887e455a491f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('on_menu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'on_menu')
    # ### end Alembic commands ###
